-- ============================================================================
-- Migration 053: relax admin_actions.action_type constraint
-- ============================================================================
-- The original CHECK constraint from 015 hardcoded a closed list of action
-- types. Since then, lib/admin.ts has grown new action types that don't match:
--
--   • approve_verification
--   • reject_verification
--   • report_actioned
--   • report_dismissed
--
-- Result: every audit-log insert for those actions has been silently failing
-- (the .insert() result is unchecked), which means admin verifications and
-- report resolutions have *no* paper trail.
--
-- Fix: drop the CHECK constraint. action_type stays a free-form text column —
-- adding a new admin action type no longer requires a migration. If we ever
-- want a closed enum we can add it back later, but the maintenance cost
-- exceeds the value of the constraint.
-- ============================================================================

-- The constraint name is auto-generated by Postgres from the column. Be safe
-- and find it dynamically.
DO $$
DECLARE
  v_constraint_name text;
BEGIN
  SELECT conname INTO v_constraint_name
  FROM pg_constraint
  WHERE conrelid = 'public.admin_actions'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%action_type%';

  IF v_constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE admin_actions DROP CONSTRAINT %I', v_constraint_name);
  END IF;
END $$;
